"""Add user table metadata

Revision ID: 47bcf3b7db3b
Revises: cbea1376ab4e
Create Date: 2023-09-26 11:05:57.479827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bcf3b7db3b'
down_revision: Union[str, None] = 'cbea1376ab4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('facebook_account', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('google_account', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('singles_skill', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('doubles_skill', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('registration_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('registration_otp_expiration', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_verify', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_verify')
    op.drop_column('users', 'registration_otp_expiration')
    op.drop_column('users', 'registration_otp')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'doubles_skill')
    op.drop_column('users', 'singles_skill')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'google_account')
    op.drop_column('users', 'facebook_account')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
